spring:
  # Production DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_URL}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  # 이메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true
        debug: false

# OAuth 시크릿 정보
app:
  oauth:
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}
      redirect-uri: ${KAKAO_REDIRECT_URI}
      scope: ${KAKAO_SCOPE}
    naver:
      client-id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}
      redirect-uri : ${NAVER_REDIRECT_URI}
      state: ${NAVER_STATE}
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: ${GOOGLE_REDIRECT_URI}
      scope: ${GOOGLE_SCOPE}
  cors:
    credential-cookie-domain: api.aimsharp.co.kr # 인증 관련 쿠키 (서버로 전송)
    client-cookie-domain: .aimsharp.co.kr # 클라이언트 저장 쿠키 (클라이언트 사용)
    allowed-origins:
      - http://localhost
      - http://localhost:3000
      - http://localhost:8080
      - http://127.0.0.1
      - http://127.0.0.1:3000
      - http://127.0.0.1:8080
    allowed-methods:
      - GET
      - POST
      - OPTIONS
      - PATCH
      - PUT
      - DELETE
    allowed-headers:
      - Origin
      - Accept
      - Accept-Language
      - Accept-Encoding
      - Content-Type
      - Access-Control-Request-Method
      - Access-Control-Request-Headers
      - Authorization
      - Cookie
      - Set-cookie
      - User-Agent
      - Cache-Control
      - Connection
      - Referer
      - X-Requested-With
      - X-Forwarded-For
      - Proxy-Client-IP
      - WL-Proxy-Client-IP
      - HTTP_CLIENT_IP
      - HTTP_X_FORWARDED_FOR
      - X-Real-IP
      - X-RealIP
      - REMOTE_ADDR

# 실제 운영중인 서버의 Port 번호는 8080
server:
  port: 8080