spring:
  # Production DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_URL}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  # 이메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true
        debug: false

# OAuth 시크릿 정보
app:
  oauth:
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}
      redirect-uri: ${KAKAO_REDIRECT_URI}
      scope: ${KAKAO_SCOPE}
    naver:
      client-id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}
      redirect-uri : ${NAVER_REDIRECT_URI}
      state: ${NAVER_STATE}
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: ${GOOGLE_REDIRECT_URI}
      scope: ${GOOGLE_SCOPE}
  cors:
    allowed-origins:
      - localhost
      - localhost:3000
      - localhost:8080
      - 127.0.0.1
      - 127.0.0.1:3000
      - 127.0.0.1:8080
    allowed-methods:
      - GET
      - POST
      - OPTION
      - PATCH
      - PUT
      - DELETE
    allowed-headers:
      - Set-cookie
      - Authorization

# 실제 운영중인 서버의 Port 번호는 8080
server:
  port: 8080