app:
  auth:
    header: auth
    secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd6eXoxMjMxMjMxMjMxMjMxMjMxMzEyMzEyMzEzMTIzMTIzMTIzMTMxMjMxMzEzMTMxMjM
    access-token-validity: 3600000 # 60분
    refresh-token-validity: 2592000000 # 30일
